import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";
import withSerwistInit from "@serwist/next";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

const withSerwist = withSerwistInit({
  swSrc: "src/app/sw.ts",
  swDest: "public/sw.js",
  // The service worker is only generated by `next build` (webpack). Dev uses Turbopack.
  disable: process.env.NODE_ENV === "development",
  // The offline fallback page must be in the cache before it is ever needed.
  additionalPrecacheEntries: [{ url: "/offline", revision: String(Date.now()) }],
});

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // The catalogues are read from disk at request time; list them so the function bundles carry them.
  outputFileTracingIncludes: { "/**": ["./data/pois/*.json", "./data/world/*.json", "./data/venues/*.json"] },
  experimental: {
    // Inline the (small) global stylesheet into the HTML: one render-blocking request less on first paint.
    inlineCss: true,
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "upload.wikimedia.org" },
      { protocol: "https", hostname: "flagcdn.com" },
    ],
  },
};

export default withSerwist(withNextIntl(nextConfig));
