import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";
import withSerwistInit from "@serwist/next";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

const withSerwist = withSerwistInit({
  swSrc: "src/app/sw.ts",
  swDest: "public/sw.js",
  // The service worker is only generated by `next build` (webpack). Dev uses Turbopack.
  disable: process.env.NODE_ENV === "development",
  // The offline fallback page must be in the cache before it is ever needed.
  additionalPrecacheEntries: [{ url: "/offline", revision: String(Date.now()) }],
});

const nextConfig: NextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "upload.wikimedia.org" },
      { protocol: "https", hostname: "flagcdn.com" },
    ],
  },
};

export default withSerwist(withNextIntl(nextConfig));
